(ert-deftest check-if-file-produced ()
  (message "Check if file produced")
  (let ((pdf1 (latexdiff-testcase-pdf1))
        (dummypdf (latexdiff-testcase-dummy-pdf)))
    (should (latexdiff--check-if-file-produced pdf1))
    (should (not (latexdiff--check-if-file-produced dummypdf)))))
