(ert-deftest check-clean ()
  (let* ((file1 (latexdiff-testcase-file1))
         (latexdiff-auto-clean-aux nil)
         (rev1 (latexdiff-testcase-rev1)))
    (with-current-buffer (find-file-noselect file1)
      (let* ((diff-file (latexdiff-vc--compile-diff-with-current rev1))
             (fileaux (format "%s.out" (file-name-sans-extension diff-file)))
             (filetex (format "%s.tex" (file-name-sans-extension diff-file)))
             (filepdf (format "%s.pdf" (file-name-sans-extension diff-file))))
        (while latexdiff-runningp (sleep-for 1))
        (should (file-exists-p fileaux))
        (should (file-exists-p filetex))
        (should (file-exists-p filepdf))
        (latexdiff-clean)
        (sleep-for 2)
        (should (not (file-exists-p fileaux)))
        (should (not (file-exists-p filepdf)))
        (should (not (file-exists-p filetex)))
        ))))
